version: '3.8'

networks:
  app_network:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

    env_file:
      - .env

    depends_on:
      - db
    networks:
      - app_network

  db:
    image: postgres:15
    container_name: postgres-eater
    env_file:
      - .env

    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

volumes:
  postgres_data:










